### ISSUE TITLE
建议提供明确的待翻译内容，否则意向贡献者不知如何下手~

### ISSUE THREAD

**Issue by hstarorg** [docschina/stylelint#33]

**Comment by hstarorg** [comment]
居然直接修改我的issue内容~这玩法有点凶残。
更好的建议是：创建一个新的Issue，关联我这个issue，然后把我这个issue关掉。

**Comment by hstarorg** [comment]
另外，建议把需要翻译的文档，创建为Issue（一个文档一个），然后采取认领模式。否则，大家容易重复工作，也并不清楚哪些内容是否在翻译中。

**Comment by gucong3000** [comment]
> 更好的建议是：创建一个新的Issue

已迁移至这里：#39

> 建议把需要翻译的文档，创建为 Issue（一个文档一个）

我会认真考虑您的建议，目前除了规则文档和 processors 相关部分外，均已完成翻译。但由于规则文档剩余 100 个，每个文档一个 issue 的话恐怕有点吃力。

**Comment by hstarorg** [comment]
@gucong3000 可以用issue列大纲，有人认领了，再自行创建issue，并统一展示进行中和待领取的任务。

**Comment by gucong3000** [comment]
issue中的大纲目前没有，文档中的倒是有一个，已在“翻译指南”添加链接。

和您建议的任务领取建议不同，我在“翻译指南”中建议直接开标题前缀为“[翻译中]”的PR，以便翻译过程更透明，及早发现翻译问题。不知您是否还坚持原来的意见。

**Comment by hstarorg** [comment]
这个也是可以的。现在有一个比较大的问题就是：如果想要贡献翻译，还需要到处找需要翻译的内容。没有一个明确的列表。如果有这样一个Issue是不是更好：

Issue Name：翻译任务领取

- [ ] XXX - 待翻译
- [ ] XXX - 待翻译
- [x] XXX - 已翻译 [具体地址](具体地址)
